### PR TITLE
Support fluent-package

### PR DESCRIPTION
**Pull request by kenhys**
To support fluent-package, introduced fluent_package? predicate and check fluent-package specific path or environment variable.

### CODE REVIEW

**Comment by kenhys** [comment]
Note #9 #10 #11 must be merged in advance.

**Comment by kenhys** [comment]
@kubotat could you review this PR?

**Comment by ashie** [comment]
We are going to release fluent-package (td-agent) v5 next week, and we want to include revised version of this gem into it.
@kubotat If you are OK, could you give us ownership of this gem on RubyGems to collaborate maintaining this gem?

* @kenhys https://rubygems.org/profiles/kenhys
* @ashie https://rubygems.org/profiles/ashie
* @daipom https://rubygems.org/profiles/daipom

In addition, can I give them write permission to this repository?
(I already have it because I'm an owner of fluent organization.)

**Comment by kubotat** [comment]
@kenhys I'm sorry for the late reply. I just merged PR #9 #10 and #11 . 
@ashie I'll give you ownwership of this gem.

**Comment by kubotat** [comment]
@ashie I just give an ownership to the following members.
- @kenhys https://rubygems.org/profiles/kenhys
- @ashie https://rubygems.org/profiles/ashie
- @daipom https://rubygems.org/profiles/daipom

Will review the PR quickly and get back to you.

**Comment by ashie** [comment]
> @ashie I just give an ownership to the following members.

I've got it, thanks!

BTW fluent-package v5.0.1 (GA) has been released yesterday.

* https://github.com/fluent/fluent-package-builder/releases/tag/v5.0.1
* https://www.fluentd.org/blog/upgrade-td-agent-v4-to-v5
* https://www.fluentd.org/blog/fluent-package-scheduled-lifecycle
* https://www.fluentd.org/blog/schedule-for-td-agent-4-eol

So I'm sorry but we couldn't ship this fix with that release.
We'll ship it with next bug fix release.

**Comment by kubotat** [comment]
@kenhys I checked that fixed diagtool works with fluent-package v5.0.1. I will merge it.
Thanks for the contribution!

**Comment by kenhys** [comment]
@kubotat Thanks!!!

**Comment by kenhys** [comment]
Confirmed gem ownership. Thanks!

**Comment by daipom** [comment]
I confirmed too! Thanks!

**Pull request merged**
